name: Iso building
concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
on:
  workflow_dispatch:
jobs:
  iso:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       include:
         - spec: "derivos"
           name: "derivOS"
    steps:
    - uses: actions/checkout@v2
    - uses: fkirc/skip-duplicate-actions@master
    - name: Install Luet and deps 🔧
      run: |
        sudo apt-get install -y xorriso squashfs-tools dosfstools
        curl https://get.mocaccino.org/luet/get_luet_root.sh | sudo sh
        sudo luet install -y repository/mocaccino-extra
        sudo luet install -y utils/jq utils/yq extension/makeiso
    - name: ${{matrix.name}} ISO Build 🔧
      env:
        LUET_NOLOCK: "true"
        LUET_CONFIG_PROTECT_SKIP: "true"
        SPEC: ${{matrix.spec}}
      run: |
            sudo -E HTTP_TIMEOUT="900" luet-makeiso $SPEC.yaml
            mkdir isobuild
            mv *.iso *.sha256 isobuild/
    - uses: actions/upload-artifact@v2
      with:
        name: mOS-${{ matrix.spec }}.iso.zip
        path: |
          isobuild/*.iso
          isobuild/*.sha256
          
  # release:
  #     if: startsWith(github.ref, 'refs/tags/')
  #     runs-on: ubuntu-latest
  #     needs: tests
  #     strategy:
  #       matrix:
  #        include:
  #        - spec: "derivos"
  #          name: "derivOS"
  #     steps:
  #     - uses: actions/checkout@v2
  #     - name: Download ISO
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: mOS-${{ matrix.spec }}.iso.zip
  #         path: release
  #     - name: Release
  #       uses: fnkr/github-action-ghr@v1
  #       if: startsWith(github.ref, 'refs/tags/')
  #       env:
  #         GHR_PATH: release/
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GHR_COMPRESS: xz